services:
  - type: web
    name: Grade-AI-Backend_Service
    env: docker
    buildCommand: docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
    startCommand: docker exec -it ollama ollama run llama3
