services:
  - type: web
    name: Grade-AI-Backend_Service
    env: docker
    buildCommand: docker build -t grade-ai-backend_service .
    startCommand: docker run -p $PORT:$PORT grade-ai-backend_service